# yaml-language-server: $schema=http://frigate_host:5000/api/config/schema.json
version: 0.16-0

mqtt:
  enabled: false

cameras:
  reolink:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.1.180:554/h264Preview_01_main
          roles:
            - detect
            - record
      # tcp seems to cut down on artifacts (verified packets)
      input_args:
        -rtsp_transport tcp

detect:
  enabled: true

# nvidia detector & model
detectors:
  onnx_0:
    type: onnx

# built from this notebook
# https://colab.research.google.com/github/blakeblackshear/frigate/blob/dev/notebooks/YOLO_NAS_Pretrained_Export.ipynb
model:
  model_type: yolonas
  width: 480
  height: 640
  input_pixel_format: bgr
  input_tensor: nchw
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

record:
  enabled: True
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
