mqtt:
  enabled: false

cameras:
  hikvision:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.3:554/streaming/channels/101  # Username/password come from env
          roles:
            - detect
            - record

    notifications:
      enabled: true
detect:
  enabled: true
version: 0.16-0
detectors:
  ov_0:
    type: openvino
    device: GPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
notifications:
  enabled: false
  email: jlotto8@gmail.com
